[package]
cairo-version = "2.12.1"
name = "dojo_simple"
version = "1.7.0-alpha.2"
edition = "2024_07"
license = "MIT"

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = ["dojo::world::world_contract::world"]

[dependencies]
dojo = { path = "../core" }
starknet = "2.12.1"

[dev-dependencies]
cairo_test = "2.12.1"
# dojo_cairo_test = { path = "../../crates/dojo/dojo-cairo-test" }

[features]
default = []

[profile.sepolia]

[cairo]
inlining-strategy = "avoid"